### ISSUE TITLE
[5.x.x] Add an option to control the automatic reverse DNS lookup

### ISSUE THREAD

**Issue by micoq** [logstash-plugins/logstash-input-tcp#100]
Since the version 5.0.0, a reverse DNS lookup is made for each client connection. Sometimes, this is not desirable.
In pure ruby, `socket.peeraddr[3]` returns by default the peer's IP address if `socket.do_not_reverse_lookup` is `true` (which seem to be the default value on the embedded jruby)
However, the behavior is different in the java loop where `channel_addr.get_host_name` is always called and can do reverse lookups
(see the [getHostName() javadoc](https://docs.oracle.com/javase/7/docs/api/java/net/InetSocketAddress.html#getHostName()))

It would be nice to have an option to enable or disable the lookups for all cases.

**Comment by yaauie** [comment]
A configurable option was added in version 5.1.0 of this plugin via #121:

~~~ ruby
input {
  tcp {
    # ...
    dns_reverse_lookup_enabled => false
  }
}
~~~
