### ISSUE TITLE
Parameter for SSL Version

### ISSUE THREAD

**Issue by Marcel-Hillmann** [logstash-plugins/logstash-input-tcp#127]
Currently Logstash is running with TLSv1/SSLv3 and it would be nice to have a parameter to set the ssl_version.

The jruby-openssl library is offering a setter function for that.

E.g.
input {
     tcp {
        port => 12345
        codec => json
        **ssl_version => [ "TLSv1.1", "TLSv1.2"]**
      }
}

Maybe a parameter with Cipher selectors would be interesting too.

Thanks
Marcel

**Comment by abraxxa** [comment]
We'd need this enhancement as well and the list of ciphers.

**Comment by murangoo** [comment]
Have you any new information about it?

**Comment by komajaro** [comment]
bump

**Comment by murangoo** [comment]
Any news?

**Comment by pawel-blm** [comment]
Hello!
Any news about this feature?

**Comment by tylerhoo** [comment]
We would also like to see this implemented as our security department requires that we disable TLS below 1.2 and only allow a specific lists of ciphers. Thank you
