### ISSUE TITLE
Request to add additional info to errors for easier tracking

### ISSUE THREAD

**Issue by AccidentallyTheCable** [logstash-plugins/logstash-input-tcp#135]
While trying to track down an error with SSL, I found it very difficult to track down which pipeline(s)/inputs were actually causing the problem. As a result, I had to get into the code of the tcp input to add some additional info to logger calls in order to determine which pipelines were causing problems.

I'd like to submit a patch for it. I'm running on an older logstash version (6.4.0) and logstash tcp input (logstash-input-tcp-5.0.9-java), but the entry is still a valid use case none the less. Patch below (based on master branch)

**Comment by AccidentallyTheCable** [comment]
[logstash-tcp-input.logging.patch.txt](https://github.com/logstash-plugins/logstash-input-tcp/files/2664635/logstash-tcp-input.logging.patch.txt)

**Comment by colinsurprenant** [comment]
@AccidentallyTheCable thanks for your contribution. 

I totally understand your concern and you are not alone, this is a growing pain (with multiple pipelines etc)  to get more contextual information into the logs to help in situations like yours. 

I looked at your patch and also took a step back and looked at the larger issue and realized we are in fact moving forward with some proposals to improve on this, see elastic/logstash/pull/9991 and elastic/logstash/issues/9988.

As much as your patch provides some more informations in the logs for this specific plugin, I would prefer that we look at this problem more globally and move forward with something that will help with all plugins, not just the tcp input. I will be following up on both issue/PR above.

Let me know if this makes sense. I'll followup here to get your feedback once we have some progress so you can let us know if this will be helpful to you.

**Comment by kares** [comment]
plugin.id context is now provided by LS, closing the proposal as defunct
