### ISSUE TITLE
Logstash-input-tcp - disabling TLS < 1.2 does not work

### ISSUE THREAD

**Issue by komajaro** [logstash-plugins/logstash-input-tcp#148]
Hello

Despite having following lines in /$logstash_configuration_directory/ jvm.options:
-Ddeployment.security.SSLv3=false
-Ddeployment.security.TLSv1=false
-Ddeployment.security.TLSv1.1=false
-Ddeployment.security.TLSv1.2=true

testing connection with openssl s_client I see disabled protocols: TLS1.0 and TLS1.1:

1.
[<logstash_user>@<hostname> logstash]$ openssl s_client -connect <hostname>:<port> -tls1 | grep Protocol
[truncated]
    Protocol  : TLSv1

2.
[<logstash_user>@<hostname> logstash]$ openssl s_client -connect <hostname>:<port> -no_tls1_2 | grep Protocol
[truncated]
    Protocol  : TLSv1.1

LS version: 6.7.1
java version: 1.8.0_191
logstash-input-tcp version: (5.2.2)

java settings:
grep tls.disabledAlgorithms  ../jre/lib/security/java.security
jdk.tls.disabledAlgorithms=SSLv3, TLSv1, RC4, MD5, DSA, DESede, DES, DH keySize < 2048, EC keySize < 224

Related issue: https://github.com/logstash-plugins/logstash-input-tcp/issues/127

**Comment by murangoo** [comment]
Hello, Any news?

**Comment by komajaro** [comment]
bump

**Comment by ihor-sokoliuk-exa** [comment]
Is there any possible workaround while PR #198 is being reviewed?

**Comment by kares** [comment]
Yes, there's a work-around to disable particular algorithms by changing the JDK's java security configuration.
Going to answer this while looking at the issue description as it touched upon the subject ...

> Despite having following lines in /$logstash_configuration_directory/ jvm.options:
-Ddeployment.security.SSLv3=false
-Ddeployment.security.TLSv1=false
-Ddeployment.security.TLSv1.1=false
-Ddeployment.security.TLSv1.2=true

Not sure where this came from, there isn't anything like `-Ddeployment.security` settings that would be advised in the Logstash/plugin documentation or the JDK documentation.

> java settings:
grep tls.disabledAlgorithms ../jre/lib/security/java.security
jdk.tls.disabledAlgorithms=SSLv3, TLSv1, RC4, MD5, DSA, DESede, DES, DH keySize < 2048, EC keySize < 224

This is the thorough way to enable/disable TLS versions in the JDK configuration (in this case one would need to add `TLSv1.1` entry to the disabledAlgorithms list). In recent LS 7.x and 8.x the JDK is bundled with Logstash (unless one downloads a no-jdk artifact) and the security file is to be found at **`$LS_HOME/jdk/conf/security/java.security`**.

Alternatively setting `‑Djdk.tls.client.protocols="TLSv1.2,TLSv1.3"` could also work in client mode.

Please note that these setting also have consequences to other functionality/plugins in Logstash that would use the Java SSL stack e.g. the Elasticsearch output.

**Comment by ihor-sokoliuk-exa** [comment]
Thank you @kares for your response. Unfortunately, I've tried this already and it doesn't work on the latest Logstash version anymore.

**Comment by kares** [comment]
interesting, this itself must be a JDK issue than or maybe a different JDK is being used?
hopefully its resolved by now, if not please share information about your env for others (Java version, OS).
editing *java.security* file is expected to globally change the SSL engine behavior, the plugin itself relies on the underlying SSL engine and the TLS versions that are disabled/enabled.

**Comment by ihor-sokoliuk-exa** [comment]
@kares the workaround was to use an older version of the tcp input plugin

**Comment by kares** [comment]
> the workaround was to use an older version of the tcp input plugin

could you maybe please clarify, for reference, assuming you tried latest 6.2.7 on LS 6.8 and than downgraded back?

**Comment by AnandhkumarG** [comment]
> > the workaround was to use an older version of the tcp input plugin
> 
> could you maybe please clarify, for reference, assuming you tried latest 6.2.7 on LS 6.8 and than downgraded back?

Hi, any updates on this? We are facing the same issue. ES/LS 6.8.23 running on jre 1.8.0_231. Logstash input plugin version 5.4  listening on 6514 rsyslog.. Though we have restricted TLS version in java security file and in ES custom config file, we could see TLS1.0 and TLS 1.1 accessible in openssl

**Comment by jsvd** [comment]
A lot of things have changed since 6.x, but testing with recent Logstash 8.4.1 with the bundled JDK, allowing only tlsv1.1 works, with the following steps:

1. removing "TLSv1.1" from `LOGSTASH_HOME/jdk.app/Contents/Home/conf/security/java.security`
2. starting logstash with the following pipeline:
```
input {
  tcp {
    port => 3333
    ssl_enable => true
    ssl_cert => '/path/to/server.crt'
    ssl_key => '/path/to/server.key'
    ssl_certificate_authorities => ['/path/to/ca.crt']
    ssl_supported_protocols => ['TLSv1.1']
  }
}
output { .. }
```

Results in:

`openssl s_client -host 127.0.0.1 -port 3333 -CAfile ca.crt -tls1` ❌
`openssl s_client -host 127.0.0.1 -port 3333 -CAfile ca.crt -tls1_1` ✅ 
`openssl s_client -host 127.0.0.1 -port 3333 -CAfile ca.crt -tls1_2` ❌

If you still having trouble with this in recent versions of Logstash and the tcp input, please open a new issue.

**Comment by AnandhkumarG** [comment]
> A lot of things have changed since 6.x, but testing with recent Logstash 8.4.1 with the bundled JDK, allowing only tlsv1.1 works, with the following steps:
> 
> 1. removing "TLSv1.1" from `LOGSTASH_HOME/jdk.app/Contents/Home/conf/security/java.security` ([as documented](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-tcp.html#plugins-inputs-tcp-ssl_supported_protocols))
> 2. starting logstash with the following pipeline:
> 
> ```
> input {
>   tcp {
>     port => 3333
>     ssl_enable => true
>     ssl_cert => '/path/to/server.crt'
>     ssl_key => '/path/to/server.key'
>     ssl_certificate_authorities => ['/path/to/ca.crt']
>     ssl_supported_protocols => ['TLSv1.1']
>   }
> }
> output { .. }
> ```
> 
> Results in:
> 
> `openssl s_client -host 127.0.0.1 -port 3333 -CAfile ca.crt -tls1` ❌ `openssl s_client -host 127.0.0.1 -port 3333 -CAfile ca.crt -tls1_1` ✅ `openssl s_client -host 127.0.0.1 -port 3333 -CAfile ca.crt -tls1_2` ❌
> 
> If you still having trouble with this in recent versions of Logstash and the tcp input, please open a new issue.

Hi , Thanks for your reply. We are currently on 6.8.23 in production and looking for options in this version currently. Could you please let know if the support for restricting TLS in JRE level is available also in 6.x version as we could not see it in documentation as well. We can raise a separate issue for 6.8 as well if needed.

**Comment by epadmav** [comment]
Hi, with reference to the above trailing discussion In 6.8.23 Logstash, we have followed the below-mentioned approaches to disable TLSv1, TLSv1.1.

1)Modified /usr/java/jdk1.8.0_231-amd64/jre/lib/security/java.security with the below content:

jdk.tls.disabledAlgorithms=SSLv3, TLSv1, TLSv1.1 keySize < 2048, \
    RC4, DES, MD5withRSA, DH keySize < 1024, \
    EC keySize < 224, 3DES_EDE_CBC, anon, NULL

Still TLSv1, TLSv1.1 is not disabled.

2)Tried disabling TLSv1, TLSv1.1 through custom security configuration setup by following the below steps:

a)	Created a directory jvm.options.d in /etc/logstash/conf.d
b)	Created a file java.security.options in /etc/logstash/conf.d/jvm.options.d 
c)	Appended the below content in /etc/logstash/conf.d/jvm.options.d/java.security.options
-Djava.security.properties=/etc/logstash/es.java.security
d)   Created a file es.java.security in /etc/logstash directory
e)   Added the below content in es.java.security file

     jdk.tls.disabledAlgorithms=SSLv3, TLSv1, TLSv1.1, RC4, DES, MD5withRSA, \
     DH keySize < 1024, EC keySize < 224, 3DES_EDE_CBC, anon, NULL 
	 
This approach is also not working in logstash 6.8.23 version. Could you please let me know if any other configuration changes need to be done or if there is any alternate approach to disable TLSv1,TLSv1.1 in logstash 6.8.23 version? Thanks in Advance
