### ISSUE TITLE
Implement ECS-Compatibility Mode

### ISSUE THREAD

**Issue by yaauie** [logstash-plugins/logstash-input-tcp#149]
_This is a stub issue, and needs to be fleshed out with details specific to
this plugin._

***

As a part of the effort to make plugins able to run in an ECS-Compatible manner
by default in an upcoming release of Logstash, this plugin needs to either
implement an ECS-Compatibility mode or certify that it does not implicitly use
fields that conflict with ECS.

**Comment by farrp** [comment]
The host field should be host.name. 

The "headers" field in the document root contains many fields that have proper ECS locations:
"headers" => {
"http_version" => "HTTP/1.1",
"request_path" => "/my/url/path",
"accept_encoding" => "gzip, compressed",
"http_accept" => nil,
"http_user_agent" => "mozilla/5.0",
"http_host" => "172.31.x.x:443",
"request_method" => "GET",
"connection" => "close",
"content_length" => "0"
}

**Comment by yaauie** [comment]
Resolved in #165
