### ISSUE TITLE
logging connection reset errors on health-checks

### ISSUE THREAD

**Issue by kares** [logstash-plugins/logstash-input-tcp#167]
currently when doing health-checks (e.g. when behind HAProxy) against the port the plugin will log the connection reset:
```
[2021-01-29T14:49:40,360][ERROR][logstash.inputs.tcp ] Error in Netty pipeline: java.io.IOException: Connection reset by peer
```

plugin does assume all traffic arriving is one to receive data from, which is legit but potentially can be improved to detect tcp pings.

we should review logging to not log resets at the error level - `warn`/`info` level should be sufficient (more details in `debug`).

**Comment by kares** [comment]
potentially related issue: https://github.com/logstash-plugins/logstash-input-tcp/issues/164

**Comment by dizlajk** [comment]
`plugin does assume all traffic arriving is one to receive data from, which is legit but potentially can be improved to detect tcp pings.`

@kares Could you make it a feature request?
