### ISSUE TITLE
refactor shutdown sequence to use plugin.stop

### ISSUE THREAD

**Issue by jsvd** [logstash-plugins/logstash-input-tcp#17]
Change shutdown sequence to be triggered by plugin.stop instead of ShutdownSignal exception.
Also remove any calls to: shutdown, finished, finished?, running? or terminating?
This depends on https://github.com/elastic/logstash/pull/3895

**Comment by purbon** [comment]
Fixed in #8

**Comment by colinsurprenant** [comment]
closing, fixed by #8 now merged.
