### ISSUE TITLE
Refactor the test helper to not use Rspec.configure.

### ISSUE THREAD

**Issue by ph** [logstash-plugins/logstash-input-tcp#20]
We have some issues when plugins are redefining the Rspec config, see 
https://github.com/elastic/logstash/issues/3997 The easiest way is to create a simple class to extract that functionality and don't redefine rspec config option in the `spec_helper`.

See @purbon's nice implementation in https://github.com/logstash-plugins/logstash-input-udp/pull/15/files

**Comment by colinsurprenant** [comment]
fix in #21
