### ISSUE TITLE
concurrent-ruby fail after update to 2.0.5

### ISSUE THREAD

**Issue by pbmsys** [logstash-plugins/logstash-input-tcp#27]
Hi.

Updated the plugin to 2.0.5 but receives the following in my logstash.err:

RuntimeError: Logstash expects concurrent-ruby version 0.9.1 and version 0.9.2 is installed, please verify this patch: /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.0.0-java/lib/logstash/patches/silence_concurrent_ruby_warning.rb
   (root) at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.0.0-java/lib/logstash/patches/silence_concurrent_ruby_warning.rb:53
  require at org/jruby/RubyKernel.java:1040
   (root) at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.0.0-java/lib/logstash/patches.rb:1
  require at org/jruby/RubyKernel.java:1040
   (root) at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.0.0-java/lib/logstash/patches.rb:6
  require at org/jruby/RubyKernel.java:1040
   (root) at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.0.0-java/lib/logstash/environment.rb:1
  require at org/jruby/RubyKernel.java:1040
   (root) at /opt/logstash/lib/bootstrap/environment.rb:48

Logstash process exits after 15 seconds.

Any insight?

**Comment by purbon** [comment]
@pbmsys sorry you're hitting this error, as you updated the plugin, the plugin manager updated their dependencies causing this bug because of a wrong dependency constraints in 2.0. For now there is not much you can do, unless you're willing to "hack" a bit your installation. Is updating logstash an option? in new versions you will not hit this issue.

**Comment by purbon** [comment]
BTW, this is not a tcp input problem, is a logstash core problem, opening an issue now.

**Comment by purbon** [comment]
Closing this in favor of https://github.com/elastic/logstash/issues/4281 thanks a lot for your feedback. Lets continue the discussion there for alternative to fix this issue in your environment.
