### ISSUE TITLE
Allow to specify SSL certificate chain

### ISSUE THREAD

**Issue by hydrapolic** [logstash-plugins/logstash-input-tcp#3]
If we have a certificate that is signed with intermediate CA that is not in the trust store then clients cannot verify the certificate.

Currently we can only set ssl_cert and ssl_key and this cert is sent to the client for verification. Would it please be possible to use Ruby's extra_chain_cert?

extra_chain_cert:
An Array of extra X509 certificates to be added to the certificate chain.

I'm using syslog-ng to send logs to logstash. On logstash end there is a TCP input:

input {
  tcp {
    port => 51000
    type => syslog

    ssl_enable => true
    ssl_key    => "/etc/ssl/cert.key"
    ssl_cert   => "/etc/ssl/cert.pem"
  }  
}

Syslog-ng:
destination loghost { tcp("host" port(51000) tls(peer-verify("required-trusted")) ); };
log { source(src); destination(loghost); };

However I'm only seeing errors in logstash:
{:timestamp=>"2015-03-05T14:44:10.322000+0000", :message=>"SSL Error", :exception=>#<OpenSSL::SSL::SSLError: Received fatal alert: unknown_ca>, :backtrace=>["org/jruby/ext/openssl/SSLSocket.java:216:in `accept'", "file:/opt/logstash/vendor/jar/jruby-complete-1.7.11.jar!/META-INF/jruby.home/lib/ruby/shared/jopenssl19/openssl/ssl-internal.rb:164:in `accept'", "/opt/logstash/lib/logstash/inputs/tcp.rb:160:in `run_server'", "org/jruby/RubyKernel.java:1521:in `loop'", "/opt/logstash/lib/logstash/inputs/tcp.rb:157:in `run_server'", "/opt/logstash/lib/logstash/inputs/tcp.rb:148:in `run'", "/opt/logstash/lib/logstash/pipeline.rb:163:in `inputworker'", "/opt/logstash/lib/logstash/pipeline.rb:157:in `start_input'"], :level=>:error}

If I check the the sent certificates with openssl s_client:
openssl s_client -host host -port 51000 -showcerts

I only see the first certificate (even though I specified the whole chain in cert.pem).

**Comment by purbon** [comment]
Fixed in #28

**Comment by hydrapolic** [comment]
Thanks!
