### ISSUE TITLE
Add client port to use in multiline filter stream identity

### ISSUE THREAD

**Issue by doubret** [logstash-plugins/logstash-input-tcp#4]
In my case i have several tcp connections from the same host on a logstash tcp input.
When i use the multiline filter, i need to setup a different stream identity for each connection so that multiline can recompose the messages correctly.
For this i needed to modify the tcp.rb code to expose the port of the client connection (only host was exposed).

Would it be possible to make this available in the official plugin ?
Thanks.

**Comment by jordansissel** [comment]
Could you use the multiline codec instead? It doesn't need stream identity because each stream runs with its own codec, and the multiline codec exists to help solve this kind of thing.

**Comment by doubret** [comment]
Good point, i will look into it !
The only thing i need to check is that it works with  charset => "CP1252".
I use NxLog as a log forwarder and then  charset => "CP1252" is important.
I will let you know if the multiline code worked.

Anyway, it makes sense to expose the port. In fact i listen on 3 tcp ports, on each port the format of incoming messages is the same, each port collects events from different type of sources but messages share the same format. It made sense to use the multiline filter because it saves from writing the multiline codec three times...

Thank you.

**Comment by jordansissel** [comment]
@doubret for now, you can work around this by using `add_field`

```
input {
  tcp {
    port => 1234
    add_field => { "port" => 1234 }
  }
}
```

**Comment by jordansissel** [comment]
> It made sense to use the multiline filter because it saves from writing the multiline codec three times...

The multiline codec will perform better because it is executed in the same thread(s) as the tcp input and avoids problems of out-of-order-messages that you'll get if you run multiple filter workers (`bin/logstash -w 4` for example).

**Comment by doubret** [comment]
Nope, i need the client port, not the server port ;)

**Comment by jordansissel** [comment]
Ahh, gotcha. I think we used to have this, but removed it from the 'host' field. Do you want the client port only? or the address and port?

**Comment by doubret** [comment]
When you suggested the codec thing i immediately thought about the thread advantage... I admit it's very temptating as i cannot increase number of workers with multiline filter.

I think i'll go for it.
But the idea of exposing client port is not a bad one i guess.

**Comment by jordansissel** [comment]
sweet. Can you file a separate ticket for the 'client port' feature request? Should be easy to fix. :)

**Comment by doubret** [comment]
adress and port should be good, anything that can identify the stream in the filter, it could be an internal identifier but the simplest is to use the client_host and client_port, it is always unique.

on the other hand providing the information in a single field is not a good idea. in the case you know you have only one connection per host on the server port, you can take advantage of this to handle disconnection/reconnection. it's not possible if you include the port directly in the same field, better to have it in a separate field imho.

**Comment by doubret** [comment]
I will file a ticket, i can put the code in the ticket if you want as i added it in the plugin on my side.
Thank you !

**Comment by jordansissel** [comment]
💚

**Comment by doubret** [comment]
There's something not working.
If i remember correctly i already tried the multiline codec but it failed to work with the CP1252 charset...

**Comment by jordansissel** [comment]
Can you show your config?

**Comment by doubret** [comment]
Here's the tcp input :

        tcp {
                port => 2508
                codec => multiline  {
                        charset => "CP1252"
                        negate => true
                        pattern => "</event>$"
                        what => next
                }
                type => "sqlagent"
        }

**Comment by jordansissel** [comment]
What's the error?

**Comment by doubret** [comment]
Not sure where it fails.
The tcp receives xml messages then i have a xml in the pipeline.
Not sure if the received message makes the xml parser fail or if the multiline codec is the problem.

One sure thing is that it breaks in the multiline codec then the error closes the tcp connection.
That's a problem because then the input is dead. The tcp input should not stop working, just discard the message.

I suspect the regex to be executed before the charset is applied...

**Comment by doubret** [comment]
The problem is coming from here (line 153 in the multine codec) :

    text.split("\n").each do |line|

The text is split against \n but doesn't take \r into account.
The \r appears in the line and it breaks.
The strange thing is that it looks like \r is not escaped...

**Comment by doubret** [comment]
I found a solution to make the multiline codec work.
I used BufferedTokenizer https://github.com/elastic/logstash/blob/master/lib/logstash/util/buftok.rb (this one is used in the line codec).

Not sure if the solution is the best aproach but it seems to work. I had to handle \r by hands though.

I'll post the code tomorrow.

**Comment by doubret** [comment]
Hi
I created a pull request with the code changes.

**Comment by purbon** [comment]
Closing this as #5 got merged.
