### ISSUE TITLE
Please update README if plugin is not maintained 

### ISSUE THREAD

**Issue by pik** [logstash-plugins/logstash-input-tcp#40]
Hello, 
As you can see there are at least 3 open related issues: #11, #34, #35. All of them involve SSLErrors which crash the entire logstash daemon. 

The first dates back to  May 18, 2015. A quick and dirty (30 minute python script) performs better than logstash-input-tcp https://github.com/logstash-plugins/logstash-input-tcp/issues/34#issuecomment-171525525. 

Logging is very much a critical piece of core infrastructure. The problem is not that certain SSL connections are broken, but that a broken SSL connection can crash the entire logstash process.
This isn't a bad peer or an openssl versioning problem (I'm running the official logstash docker image btw) because even if all the peers are good, the very possibility of an DOS attack through this is already critically bad. 
If no one is able to maintain this gem please update the README to reflect this. A plugin listed on the official docs, whose use is encouraged but is ultimately broken, is not doing anyone a service. It may also make sense to ask someone from the community to take over maintenance - but the current situation seems quite poor.

**Comment by purbon** [comment]
Good morning, 
   first I feel sorry for your pain, I understand the issues. Although I this plugin is maintained, we've a ton of  plugins to cover making very hard to be up to date with all of them. Having said that I would try to provide some guide to your issues here.

re: errors that make the entire logstash daemon to crash, please open an issue at https://github.com/elastic/logstash, there it will get the necessary attention for sure as this is a very important kind of errors.

re: performance, this also makes sense as the logstash-input-tcp have more stuff happening around it than a plain python script. Would be nice if you can share numbers that compare both solutions. Always looking for reasonable benchmarks :+1: 

Closing this issue as the plugin is maintained.

**Comment by pik** [comment]
@purbon 
> re: performance,

I think I should have clarified - what I mean is that SSLErrors listed in the issues above will prevent Logstash and logstash-tcp-input from working, even a try-except block that throws away a bad peer (okay we lose some data, but we can log the errors as warn/critical - which is merely what I did in the python script) is far better than crashing the entire plugin. It's very hard to call this maintained when the first issue was opened in May!
