### ISSUE TITLE
how to set keepalive ?

### ISSUE THREAD

**Issue by mr2qin** [logstash-plugins/logstash-input-tcp#66]
- Version: 5.0.1
- Operating System:  centos7
- Config File (if you have sensitive info, please remove it):
```
input {
    tcp {
        host => "0.0.0.0"
        port => 4561
        mode => "server"
        codec => json_lines
      }
}
output {
    stdout{codec =>rubydebug}
    elasticsearch {
        hosts => ["host1:9292","host2:9292"]
        flush_size => 10000
        idle_flush_time => 2
        index=>"logstash-task-%{taskId}-%{+YYYYMMdd}"
     }
}
```
Sometimes the client disconnected, but there is no disconnect the server side,  4561 the number of connections, has increased 
https://discuss.elastic.co/t/logstash-input-tcp-keepalive/82375

**Comment by red8888** [comment]
I have the same problem. TCP keep alive needs to be implemented by the application and for some reason logstash doesn't implement it. You might have to switch to a different app if you need tcp keep alive support.

**Comment by kares** [comment]
the plugin supports the `tcp_keep_alive => true` configuration option
