### ISSUE TITLE
Default cloudfoundry loggregator cipher suites not supported

### ISSUE THREAD

**Issue by lpic10** [logstash-plugins/logstash-input-tcp#72]
Cloudfoundry loggregator by default uses only the following cipher suites:

TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384

And these don't seem to be supported by jruby openssl: https://github.com/jruby/jruby/issues/1774

We have a setup where logs generated in bluemix are forwarded to an external logstash (then Elasticsearch). Since a recent change on bluemix/loggregator that limits the cipher suites to these, this setup does not work anymore (requiring another component for the tls termination). 

Thus that makes impossible the simple usage of logstash to receive logs from Bluemix using syslog+tls (encryption being a requirement for us).

https://console.bluemix.net/docs/monitor_log/logging/external/logging_external_hosts.html#thirdparty_logging

**Comment by kares** [comment]
ciphers should be support by now
