### ISSUE TITLE
version file incorrectly specified in gemspec definition

### ISSUE THREAD

**Issue by robbavey** [logstash-plugins/logstash-input-tcp#73]
As @jakelandis mentions in https://github.com/elastic/logstash/issues/7574#issuecomment-312132206, the version file referenced in https://github.com/logstash-plugins/logstash-input-tcp/blob/master/lib/logstash-input-tcp_jars.rb#L4 is incorrectly specified in the gemspec files list

**Comment by original-brownbear** [comment]
@robbavey yikes :) on it

**Comment by original-brownbear** [comment]
fixed in #74
