### ISSUE TITLE
Optionally perfer hostname of IP for host field

### ISSUE THREAD

**Issue by jakelandis** [logstash-plugins/logstash-input-tcp#78]
To better consolidate the representation of the ```host``` field,  this plugin should optionally use the hostname in favor of the IPaddress to better match other plugins use of Socket.gethostname. (which is backed by InetAddress.getLocalHost().getHostName() in JRuby). 

I am not sure why TCP input chose IP address. Note the ruby implementation uses [s.peeraddr[3]](https://github.com/logstash-plugins/logstash-input-tcp/blob/v4.1.2/lib/logstash/inputs/tcp.rb#L195) which maps the IP address, and the java version preserves this behavior.  

Perhaps it is latent bug in the TCP input, where the intention was to use hostname, but is an off by one error ?

It seems that other plugins are resulting in the host name not IP, which may cause issues with ES mappings.

**Comment by jakelandis** [comment]
Relevant issue : https://github.com/logstash-plugins/logstash-input-tcp/issues/75

**Comment by original-brownbear** [comment]
@jakelandis not sure I fully understand the connection to #75 here sorry :)

#75 is about the way we resolve the hostname of a peer connecting inbound?
Either we reverse resolve its address or we don't right? (Currently, we do as far as I know)

Are you suggesting that we make the reverse lookup optional? (I like the idea :D, but I feel like I'm missing something :))

**Comment by jakelandis** [comment]
#75 was a regression that took the ```host``` field from IP -> Hostname

I references it since the PR for it shows the code changes for IP vs. Hostname. 

Also, if we wanted to non-passively change this (e.g. don't make it optional), we could simply revert that PR.

**Comment by original-brownbear** [comment]
@jakelandis ah :) now I see, sorry this is really confusing. But I agree, we should try to do what the other plugins do. If this is the only plugin with this behavior we should revert #76.

**Comment by suyograo** [comment]
I am +1 for changing this to reflect hostname rather than IP. This is a breaking change as you've noted, so 6.0 would be a good time to do so and make it a major version bump for this plugin. To preserve some backward compatibility, thoughts on adding a new field called `host_ip` to record the IP address?

**Comment by original-brownbear** [comment]
@suyograo @jakelandis 

> To preserve some backward compatibility, thoughts on adding a new field called host_ip to record the IP address?

Makes sense to me, we could make someone that has his scripting set up to work with IPs really unhappy if he has to resolve that later on (which might not even be possible in all cases) and we have the information for free anyways :)

**Comment by jakelandis** [comment]
+1 on adding in a separate host_ip field, however we should keep the naming consistent. 

The similar was added to [beats input](https://github.com/logstash-plugins/logstash-input-beats/issues/180#issuecomment-306915744) :  ``` @metadata.ip_address```

See PR https://github.com/logstash-plugins/logstash-input-beats/commit/cc0976ba2d4448f53c7dc15899d0804c0c96661c#diff-567e96bcd40abb0b5cf8d6da5fc71340R33

**Comment by suyograo** [comment]
@jakelandis +1.
