### ISSUE TITLE
IOerror: connection reset by peer

### ISSUE THREAD

**Issue by kuongknight** [logstash-plugins/logstash-input-tcp#85]
I has > 200 client always open tcp socket and push log to logstash server by tcp input with ssl.
It work as well, but some time (after few day or few hour) tcp logstash had been crashed (i can't telnet tcp port) and I found error:![Image](http://i.imgur.com/2rnwPiq.jpg)
What was wrong here?

**Comment by jordansissel** [comment]
Connection reset by peer means the client closed the connection in an
unhealthy way and the next time logstash tried to use it it was notified of
this reset.

I recommend looking into your network (firewall interference?) or your
client (how are connections being terminated, etc)

**Comment by kuongknight** [comment]
I can't telnet on logstash sever, that mean tcp socket server had been broken. We can ignore issue by network or firewall.

**Comment by elvarb** [comment]
I'm seeing a similar problem in one setup I have, sadly I restarted the logstash service just to get it working again. There was not much in the logs to indicate why everything had stopped, but I suspect it could be related to open sockets/ports. Will see how it progresses and do more debugging if it happens again.

**Comment by kares** [comment]
since this is a very generic issue (no reproducer) and usually depends on external factors, I am calling it defunct
