### ISSUE TITLE
@metadata.ip_address is spelt metdata.ip_address in tcp.rb

### ISSUE THREAD

**Issue by nradonicich** [logstash-plugins/logstash-input-tcp#87]
The setting in 'lib/logstash/inputs/tcp.rb' line 109 is currently ` HOST_IP_FIELD = "[@metdata][ip_address]".freeze`

should this not be [@metadata][ip_address]  ?

**Comment by untergeek** [comment]
Yes.  Yes it should.  That's a great catch.  Would you like to submit it as a pull request?

**Comment by nradonicich** [comment]
submitted under https://github.com/logstash-plugins/logstash-input-tcp/commit/64cf193cb2e545e3c5ccdc7d6c1d0c1797b4dfc5. If i didn't do it right let me know... fails build in 6 and master but I dont think its because of my changes.

**Comment by Dhyrule** [comment]
I noticed this as well!

**Comment by vbohata** [comment]
Me too.

**Comment by jakelandis** [comment]
Fixed by https://github.com/logstash-plugins/logstash-input-tcp/pull/94 will be part of `5.0.3`
