### ISSUE TITLE
sslsubject field is no longer being set when ssl_verify == true

### ISSUE THREAD

**Issue by utilitynerd** [logstash-plugins/logstash-input-tcp#89]
It looks like https://github.com/logstash-plugins/logstash-input-tcp/commit/e4d4510381b427de8476df82d63961e5031fd532  broke setting the sslsubject field.

The current logstash documentation for the tcp input says when ssl_verify == true,

"Verify the identity of the other end of the SSL connection against the CA. For input, sets the field sslsubject to that of the client certificate."

- Version: logstash 5.6.3

- Operating System: RHEL 7

- Config File (if you have sensitive info, please remove it):
  tcp {
      port =>6514
      tags => ['syslog-tcp-tls']
      ssl_verify => true
      ssl_enable => true
      ssl_cert => '/etc/logstash/logstash_tls.cert'
      ssl_key => '/etc/logstash/logstash_tls.key.pk8'
      ssl_extra_chain_certs => ['/etc/logstash/logstash_tls.ca']
    }

- Steps to Reproduce:  upgrade logstash to 5.6.3 

- Expected behaviour: sslsubject gets set with CN from client certificate

- Actual behaviour: sslsubject does not get set

**Comment by utilitynerd** [comment]
Was removing the sslsubject intentional?  If so, I'd like to create an issue so the documentation gets updated.

**Comment by adamjt** [comment]
Ran into this issue as well, would love to know if it's intentional or a bug.

**Comment by utilitynerd** [comment]
It's been 2 months since this issue was filed.  Could the developers respond on whether this was a bug or an intentional change.

**Comment by utilitynerd** [comment]
Going to go ahead and close this since it hasn't even been acknowledged as a problem.  

Hopefully others who run into this problem find this issue and realize it will not be fixed.
