### ISSUE TITLE
SSL Not Working

### ISSUE THREAD

**Issue by jwensley2** [logstash-plugins/logstash-input-tcp#93]
I have a TCP input setup using SSL, my client can connect and I don't get any errors in my logs, but nothing is written to my outputs. If I disable SSL it works fine.

I don't get any errors using `openssl s_client -connect myhost:5000` either.

Pipeline config
```
input {
    tcp {
        port => 5000
        codec => json_lines

        ssl_enable => true
        ssl_cert => "/etc/logstash/ssl/k.crt"
        ssl_key => "/etc/logstash/ssl/k.p8"
    }
}

output {
    elasticsearch {
        hosts => ["es-1", "es-2"]
        ssl => true
        user => "logstash_internal"
        password => "$$PASSWORD$$"
        index => "logs-%{+YYYY.MM.dd}"
        cacert => "/etc/logstash/ssl/ca.crt"
    }

    file {
        path => "/var/log/logstash/logs.log"
        codec => "json_lines"
    }
}
```

OS: Debian 8.9
Logstash version: 6.0.0
logstash-input-tcp version: 5.0.2

**Comment by jordansissel** [comment]
I can confirm your reported behavior. I reread the Logstash tcp input docs and found that `ssl_verify` is *enabled* by default. This means the client is required to provide a valid certificate when asked by the server.

You can set `ssl_verify => false` to disable this requirement

---

While researching, here were my notes:

```
% bin/logstash -e 'input { tcp { port => 5000 codec => json_lines ssl_enable => true ssl_cert => "lumberjack.crt" ssl_key => "lumberjack.key" } }'
```

```
% openssl s_client -connect localhost:5000 -CAfile lumberjack.crt
CONNECTED(00000003)
depth=0 CN = localhost
verify return:1
140671072749376:error:14094412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate:ssl/record/rec_layer_s3.c:1399:SSL alert number 42
...
```

(exit code is 1)

tshark showing the protocol details and why it failed:

```
    4 0.000176913          ::1 → ::1          TLSv1 342 Client Hello
    5 0.000187205          ::1 → ::1          TCP 88 5000 → 59210 [ACK] Seq=1 Ack=255 Win=44800 Len=0 TSval=3855479663 TSecr=3855479663
    6 0.014062769          ::1 → ::1          TLSv1.2 1329 Server Hello, Certificate, Server Key Exchange, Certificate Request, Server Hello Done
    7 0.014114229          ::1 → ::1          TCP 88 59210 → 5000 [ACK] Seq=255 Ack=1242 Win=174720 Len=0 TSval=3855479677 TSecr=3855479677
    8 0.014873123          ::1 → ::1          TLSv1.2 282 Certificate, Client Key Exchange, Change Cipher Spec, Encrypted Handshake Message
    9 0.015714027          ::1 → ::1          TLSv1.2 95 Alert (Level: Fatal, Description: Bad Certificate)
```

The server (logstash) sends a `Certificate Request` while negotiating with the client. The client responds with a zero-length Certificate response (indicating it has no certificate to offer), and the server rejects it immediately with TLS Alert `42` (bad_certificate).

Setting `ssl_verify => false` on the tcp input will resolve this.

**Comment by jwensley2** [comment]
So I did have `ssl_verify => false` set and must of removed it from the config I posted accidentally.

While testing using `openssl s_client -connect` I noticed it was logging my input, so I think this is an issue with my client, still not sure what though.

Thanks for the help though.
