### ISSUE TITLE
TCP input is silently broken in Logstash 5.6.x

### ISSUE THREAD

**Issue by pietervogelaar** [logstash-plugins/logstash-input-tcp#95]
We have a Sensu servers that sends Sensu events with a TCP handler to Logstash. This worked fine until Logstash version 5.5.3, but it's broken in 5.6.3 and also 5.6.5. So probably the whole 5.6.x range. However no single error is logged and if I use a Logstash file output, no data is written to it with Logstash 5.6.x.

So it seems to be silently broken.

Sensu server (/etc/sensu/conf.d/handlers/logging_acc.json):
```
{
  "handlers": {
    "logging_acc": {
      "command": null,
      "type": "tcp",
      "socket": {
        "host": "logstash-host.example.org",
        "port": 5555
      },
      "filters": [
        "state_change",
        "non_production_environment"
      ],
      "severities": [
        "ok",
        "warning",
        "critical",
        "unknown"
      ],
      "handle_flapping": false,
      "handle_silenced": false
    }
  }
}
```

Logstash server (/etc/logstash/conf.d/10_input_sensu)
```
input {
  tcp {
    port => 5555
    type => "sensu"
  }
}
```

**Comment by danhermann** [comment]
This issue should be resolved as of the commit referenced above and released in v5.3.0 of the TCP input plugin.
